Get yelp data
CS411F17/project pull request #11
Opened 2017-10-23 03:13 UTC by csuksangium

2017-10-23 03:15 UTC, Simenhug approved these changes
great job

2017-10-23 04:54 UTC, freddiev4 requested changes

2017-10-23 04:54 UTC, freddiev4 commented on testapp/views.py
> +CLIENT_SECRET = 'TLPjiUfjOessjQVEqQpogquNpwNHUkMrba5QCCCASgb5fUfMhwamVNvRvB9tAy78'
I think we should remove these

2017-10-23 04:54 UTC, freddiev4 commented on testapp/views.py
> +DEFAULT_LOCATION = 'San Francisco, CA'
Should the default_location be `Boston, MA`?

2017-10-23 04:54 UTC, freddiev4 commented on testapp/views.py
> +def yelpCall(keyTerm, location):
Should we name this `yelp_call()` to be consistent in our code style?

2017-10-23 04:54 UTC, freddiev4 commented on testapp/views.py
> +  pass
Should we remove this `query_yelp()` function? It's not being used

2017-10-23 17:29 UTC, freddiev4 requested changes

2017-10-23 17:29 UTC, freddiev4 commented on testapp/yelp_clientid.yaml
> +CLIENT_SECRET = 'TLPjiUfjOessjQVEqQpogquNpwNHUkMrba5QCCCASgb5fUfMhwamVNvRvB9tAy78'
Looks like this `.yaml` file still got included in the git history. Can you remove it and fixup all the commits into one commit?

2017-10-25 00:23 UTC, freddiev4 approved these changes

2017-10-25 00:26 UTC, merged