Facebook data store
CS411F17/project pull request #37
Opened 2017-11-14 23:45 UTC by csuksangium

2017-11-14 23:57 UTC, janelljchen approved these changes

2017-11-16 03:07 UTC, freddiev4 requested changes

2017-11-16 03:07 UTC, freddiev4 commented on testapp/models.py
> +
Nit-pick but can we remove this extra whitespace?

2017-11-16 03:07 UTC, freddiev4 commented on testapp/views.py
> +#args = {'fields' : 'address'}
Do we need this bit that commented out? If not can we remove it?

2017-11-16 03:07 UTC, freddiev4 commented on testapp/views.py
> +                user_info.religion = fb_user_info['religion']
I think there might be a better approach to this, like traversing the JSON in some other way but we can come back to this for the sake of time

2017-11-16 03:07 UTC, freddiev4 commented on testapp/views.py
> +    #access_token = SocialToken.objects.filter(account__user=user.user, account__provider='facebook').first()
Can we remove this? Or are we still saving data this way?

2017-11-16 03:08 UTC, freddiev4 commented
Also looks like there's some merge conflicts here; once you address the other comments I made I can go through the conflict stuff

2017-11-16 05:04 UTC, csuksangium commented
did the formatting stuff and ill look into a cleaner way to parse the json

2017-11-16 07:03 UTC, freddiev4 approved these changes

2017-11-16 07:03 UTC, merged